### ISSUE TITLE
Schedule Exclusions Do Not Save With Certain Browser Settings

### ISSUE THREAD

**Issue by bezalelBU** [BEMADEV/Room-Management#14]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a Google Chrome browser has (Canadian) English prioritized over (United States) English, schedule exclusions are not saved in reservation edits, and the Reservation Calendar does not correctly apply exclusions. This does not happen for all schedules/exclusions, only for those applied to Room Management Reservations. 

### Expected Behavior

Expected Behavior: Adding a schedule exclusion should result in the exclusion saving to the reservation schedule, and being visible if the reservation is edited again.
Chrome browser settings:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/52384935-b6f2-414f-a2ac-932a7c98d4a3)
Correct Schedule Exclusion:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/b6e59e6f-934a-4373-91cf-3f6192573819)
Reservation is correctly excluded from the Calendar:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/25d5d7d1-2862-4e6f-bbfa-26331ac8429a)

### Actual Behavior

Actual Behavior: If the (Canadian) English language option is prioritized in the Google Chrome (or other) browser settings, the schedule exclusions in Room Management do not save correctly.
Chrome browser settings:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/eb501455-0b5d-4f71-a542-1db20371ff5f)
Blank Exclusion field:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/a7fab1cf-036c-4a93-8648-508495b85cd5)
Reservation is still visible on the Calendar:
![image](https://github.com/BEMADEV/Room-Management/assets/59073587/12a036bd-8ef0-4858-8b05-6a4ad40a7be4)

### Steps to Reproduce

- Go to 'chrome://settings/languages'
- Click on 'Add Languages'
- Scroll down and Select '(Canadian) English'
- Click 'Add' button
- Click 'More Actions' icon on (Canadian) English option
- Select 'Move to Top'
- Restart Browser
- Go to a test Reservation in Room Management Plugin
- Click 'Edit' to edit the test Reservation
- Click 'Edit Schedule'
- Click 'Add Date Range' in Exclusion category
- Enter test values for Exclusion Start and End dates
- Click 'OK' on Exclusion entry
- Click 'OK' on Schedule Edit modal
- Click 'Save' on Reservation Edit
- Go back to edit Reservation and see that the exclusion was not saved.
- Go to Reservation Calendar and verify that the exclusion does not exist.

### Rock Version

v15.1

### Plugin Version

2.3.7.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
After testing, we were able to reproduce this issue in both v14 and 15, but also in stock Rock. It looks like the issue lies in canadian dates using dashes, which breaks these lines in Core: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/ScheduleBuilder.cs#L925-L926. I recommend submitting a bug report requesting that the code be updated to the following to solve the issue:

` var dateRangeParts = dateRangeString.Split( new string[] { " - " }, StringSplitOptions.RemoveEmptyEntries );`
