### ISSUE TITLE
Detailed Calendar View not Working

### ISSUE THREAD

**Issue by mikedotmundy** [BEMADEV/Room-Management#16]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The new Detailed Calendar View is not working in our instance. We receive the error message as in this photo:
<img width="1728" alt="Screenshot 2023-10-03 at 21 37 23" src="https://github.com/BEMADEV/Room-Management/assets/23226974/1e80c027-e78e-4507-8b56-4d27d64019d3">

### Expected Behavior

Detailed Calendar View would work.

### Actual Behavior

Detailed Calendar View does not work.

### Steps to Reproduce

See above.

### Rock Version

v15.1

### Plugin Version

v2.3.9.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
We've updated the migration that adds this. In the meantime, you can go into the newly added Reservation View and remove the extra quotes around the path, so that it's surrounded by single quotes.
