### ISSUE TITLE
Don't Modify Reservation Schedule if Schedule Hasn't Changed

### ISSUE THREAD

**Issue by billdeitrick** [BEMADEV/Room-Management#20]
In certain situations with workflow triggers, it is helpful to know whether or not the schedule associated with an event has changed based on that schedule's timestamp.

In the use case driving this request, I use a "Reservation Updated" workflow trigger to detect when an exclusion has been added to a reservation's schedule. Since this action doesn't create a history entry, I am looking at the schedule's modification datetime to check if it has changed (and a history entry hasn't been generated, indicating some other change to the schedule).

Currently, a new schedule is generated when the event is saved, updating created/modification datetimes. It would be helpful if a new schedule was only created when the schedule was actually modified, so that creation/modification timestamps were more accurate. Perhaps comparing iCal strings on the old/new schedules would help with detecting changes.

**Comment by tcavaletto** [comment]
Added to Release 2.4.3.14
