### ISSUE TITLE
Http Exception When Loading Zone Editor

### ISSUE THREAD

**Issue by mikedotmundy** [BEMADEV/Room-Management#26]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When loading the Zone Editor on _any_ page, it takes anywhere from 20-30 seconds to actually pull it up. So I did a quick search in Rocket Chat, and found this thread: https://chat.rockrms.com/channel/cms?msg=dRaqgNk8C39Z4dADy

So, after reading that I looked at my exception log and found 3 exceptions that happened at the exact time I tried to pull up the Zone Editor.
<img width="1598" alt="Screenshot 2023-12-13 at 18 06 48" src="https://github.com/BEMADEV/Room-Management/assets/23226974/0bf43787-6e0d-491a-a8f6-677c651eb95b">

It seems that Rock is trying to compile some old blocks, but is running into errors. 

We originally had the Central AZ Room Management plugin, but have since upgraded to the Room Management 2.0 plugin. So, my question is, is there anything that may not have been migrated properly when installing the 2.0 plugin that is still referencing these old blocks?

### Expected Behavior

No error.

### Actual Behavior

Error as displayed above.

### Steps to Reproduce

See above

### Rock Version

v16.0, v16.1

### Plugin Version

v2.4.4.14

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
<img width="1603" alt="Screenshot 2023-12-13 at 18 33 59" src="https://github.com/BEMADEV/Room-Management/assets/23226974/94980440-d304-4a97-96cf-e6440f476dec">

**Comment by JRichmond27** [comment]
We are also seeing this with Rock v15.2 and plugin v2.4.1.14

**Comment by tcavaletto** [comment]
Hi @mikedotmundy , @JRichmond27 . This is a relatively harmless exception that's basically Rock saying 'I have a record of CentralAZ blocks in my database, but I'm not finding them on your file system. If you end up wanting to use them I don't know what to do.'

You should be able to resolve it by going to CMS Management > Block Types, and removing the old com_centralaz/RoomManagement blocks.

**Comment by mikedotmundy** [comment]
Thank you @tcavaletto! Glad to know this is harmless, but still rather annoying as it could take 30+ seconds to load the zone editor.

2 of the blocks were there and I removed them. However, this Block did not show up in the list, and it is still throwing an error any time I try to load the zone editor on any page. Thoughts?

![Screenshot 2024-01-23 at 08 51 01](https://github.com/BEMADEV/Room-Management/assets/23226974/13795f95-242d-44b3-b0f7-fa7d35b1153f)

**Comment by mikedotmundy** [comment]
It looks like it does show up under `com_bemadev`. Is it safe to delete?

![Screenshot 2024-01-23 at 08 53 50](https://github.com/BEMADEV/Room-Management/assets/23226974/702a11a2-7d5a-4c11-aa19-d8e77fb64642)
