### ISSUE TITLE
Fluid compatibility with Modification Process workflow type

### ISSUE THREAD

**Issue by smross** [BEMADEV/Room-Management#32]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a workflow of type _Modification Process_ is triggered that passes a _ModifiedByPersonAliasId_ that is null/blank, a Fluid exception is logged.

### Expected Behavior

The workflow (that ships) should handle a blank/null _ModifiedByPersonAliasId_ when the Rock system is running in Fluid mode. 

### Actual Behavior

If your Rock system is running in Fluid mode an exception is logged when the workflow is triggered, and a blank/null value exists for _ModifiedByPersonAliasId_.

**From the workflow**
![image](https://github.com/BEMADEV/Room-Management/assets/8688424/bec8ede1-ea52-485e-946d-43341fcf56ab)

**From the exception log**
![image](https://github.com/BEMADEV/Room-Management/assets/8688424/a9798700-27a9-4db3-b927-30bb994e0b55)

### Steps to Reproduce

1. Upgrade your Rock system to a version that supports the Fluid lava framework
2. Set your _Lava Engine Liquid Framework_ to _Fluid_ 
3. Trigger the _Modification Process_ Room Management Workflow Type to run

### Rock Version

14.3, 14.4 & 16.2

### Plugin Version

2.3.7.14 & 2.4.7.14

### Client Culture Setting

en-US

**Comment by smross** [comment]
@tcavaletto FYI (I'm assuming you're the person to coordinate with), we've taken steps in our Rock 16.2 instance to 'fix' this (it's not really a fix). I am thinking through how to submit another bug report, etc. to clarify independent bugs that interact with each other (below is what we did to address both in our environment)
Here's what we've done for now:

1. "Set New Approval State" action: changed logic check from "newValue > oldValue" to "newValue != oldValue" - because we want to know all changes to quantities not just increases
2. Moved 2 actions "Check if Modifier is in an Approval Group" & "End Workflow if Modifier in Approval Group" to be after the "Activate Change Approval Status Activity" - so that they are NEVER executed ... there is an issue with the ModifiedByPersonAliasId on the reservation not always reflecting who made the modification.

**Comment by tcavaletto** [comment]
@smross Do the following updates to the lava solve your issue?

`{% assign reservation = Workflow | Attribute:'Reservation','Object' %}
{% assign modifiedByPersonAliasId = reservation.ModifiedByPersonAliasId | Default:'0' %}
{% assign campusId = reservation.CampusId %}

{% sql %}
Declare @CampusId int = Try_Cast('{{campusId}}' as int )
Declare @ModifiedByPersonAliasId int = Try_Cast('{{modifiedByPersonAliasId}}' as int )
Declare @ReservationTypeId int = Try_Cast('{{reservation.ReservationTypeId}}' as int )

Select @CampusId
Select *
From _com_bemaservices_RoomManagement_ReservationType rt
Join _com_bemaservices_RoomManagement_ReservationApprovalGroup ag on ag.ReservationTypeId = rt.Id
Join [Group] g on ag.ApprovalGroupId = g.Id
Join GroupMember gm on gm.GroupMemberStatus = 1 and gm.IsArchived = 0 and gm.GroupId = g.Id
Where rt.Id = @ReservationTypeId
And gm.PersonId = @ModifiedByPersonAliasId
And (ag.CampusId is null or ag.CampusId = @CampusId)
{% endsql %}
{% assign resultCount = results | Size %}
{% if resultCount > 0 %}
Yes
{% else %}
No
{% endif %}`

Additionally, do you have an idea about the steps to cause the ModifiedByPersonAliasId to not be accurate?

**Comment by smross** [comment]
Thanks @tcavaletto !

I'll give this a go as soon as I can.

Re: the _ModifiedByPersonAliasId_, we think that will be something we want to 'bundle' together with a couple other things (some minor bugs, some feature enhancement questions), and have a conversation/meeting. I have a draft of that issue, but it's _really_ difficult to explain and make sense (everything is connected, and I don't write .net code).
So, if you have a form we should fill out for that, we're happy to do so. My plan was to go to https://rock.bemaservices.com/ and use the contact methods there.

**Comment by JRichmond27** [comment]
I just noticed that we've been running into this same issue. I tried running the code above, and it seems to get rid of the error, but I'm not sure if the output is correct or not.

When the `ModifiedByPersonAliasId` is null, it spits out "Yes". Is that correct? In other words, if there is no modifier, then the answer to "Check if Modifier is in an Approval Group" should be Yes? It seems to me like a missing modifier should NOT be considered as being in an approval group.

**Comment by JRichmond27** [comment]
Scratch that... @tcavaletto, it looks like your sample code above has an extra `Select @Campus` on line 10 right before the actual intended `Select *`. Because of the extra select, the result count is always 1, which means the answer is always Yes. 

After removing the extra select, a reservation with a missing modifier resulted in a "No" answer as I would have expected.
