### ISSUE TITLE
Override Button

### ISSUE THREAD

**Issue by marcierempel** [BEMADEV/Room-Management#34]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

After updating from the CentralAZ plugin to the Bema Room Management plugin, the override button is not visible to people in the Override Approval Group. The documentation indicates that 'Override: Always visible to the Override Approval Group, this button bypasses all approval processes and marks the reservation as Approved.'
![image](https://github.com/BEMADEV/Room-Management/assets/44587882/a3c7714e-9155-4413-9638-f1c600d019a7)

Here's a reservation that is showing PendingFinalApproval (there was no Final Approval Group set for this reservation type so it's expected that it is moved into an Approved State), but it doesn't, it stays in PendingFinalApproval and the WF shows as completed (without the booking ever being fully approved). I then tested that reservation with a Final Approval Group added, denied a room, which put it back into a Changes Needed state, then approved the room, putting it back into a PendingFinalApproval group state, but there is still no approval button or override button showing in that state.
![image](https://github.com/BEMADEV/Room-Management/assets/44587882/4b6ea57d-0f7e-493c-abcc-4703c0a86d14)
![image](https://github.com/BEMADEV/Room-Management/assets/44587882/6de4cc53-56ce-4358-8c2b-b3cffd9730e2)

In the history of this reservation, it shows that the Approval State Value changed from Pending Review to Overide: Approved
but there was never any 'override' button selected.

### Expected Behavior

Override button is available to approve any reservation by anyone in the Override Approval Group.
If no Final Approval Group, reservation should be updated to an Approved state.
If Final Approval Group is in place on reservation type, then people in that Final Approval Group should be able to Approve the booking (no Approval button or Override button is visable).

### Actual Behavior

Override button is never visible.
Approve button is not visible when trying to Approve in the PendingFinalApproval state.

### Steps to Reproduce

Not able to test this in a different environment, it may only be a bug in our instance? We've had an issue in the past with the old version of the plugin where the Deny button did not show up and had to over ride that in the block, but I'm not sure if this is the same issue?

### Rock Version

v15.3

### Plugin Version

2.4.7.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
@marcierempel We've re-added the override button in an upcoming release. In the meantime, normal Final Approval Groups are unable to approve reservations with conflicts like the one in the screenshot above.

**Comment by tcavaletto** [comment]
@marcierempel We'll be releasing this tomorrow.

**Comment by tcavaletto** [comment]
@marcierempel The new release has some features that need further testing, so we'll be delaying it. In the meantime, applying these changes should fix your immediate issue: https://github.com/BEMADEV/Room-Management/commit/23358a734c1c6dee57180eb7a4cb3839375fa6ee

**Comment by marcierempel** [comment]
Hi Taylor – Thanks for the information on the changes. Any idea on the timeline for testing and implementing the update? That will help me determine if we can wait for it or not.

Marcie

From: Taylor Cavaletto ***@***.***>
Date: Friday, February 23, 2024 at 9:27 AM
To: BEMADEV/Room-Management ***@***.***>
Cc: Marcie Rempel ***@***.***>, Mention ***@***.***>
Subject: Re: [BEMADEV/Room-Management] Override Button (Issue #34)

@marcierempel<https://github.com/marcierempel> The new release has some features that need further testing, so we'll be delaying it. In the meantime, applying these changes should fix your immediate issue: 23358a7<https://github.com/BEMADEV/Room-Management/commit/23358a734c1c6dee57180eb7a4cb3839375fa6ee>
