### ISSUE TITLE
Reservation Updated Workflows Not Fired When Resources or Locations are Updated

### ISSUE THREAD

**Issue by billdeitrick** [BEMADEV/Room-Management#36]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When resources or locations are updated on a reservation, without any other changes being made to that reservation, workflows configured to run with the Reservation Updated workflow trigger are not fired.

![Snag_1ef4b49](https://github.com/BEMADEV/Room-Management/assets/4174527/d7c548b5-231c-402b-828f-0e1f31b52a6f)

### Expected Behavior

Workflow triggers for the "Reservation Updated" trigger should fire the attached workflow when location or resource changes are made, even if no other properties on the reservation are updated.

### Actual Behavior

Reservation Updated workflow triggers are never fired if only location or resource changes are made to a reservation (adding or removing).

### Steps to Reproduce

1. Create a new reservation without any locations
2. Ensure the new reservation becomes approved
3. Add a location to the new reservation
4. Verify that Reservation Updated triggered workflows are never fired

### Rock Version

1.16.4.4

### Plugin Version

2.4.7.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Fixed issue
