### ISSUE TITLE
Internal Testing v2.5.5.14: Unable to Delete Locations or Resources from a Reservation

### ISSUE THREAD

**Issue by billdeitrick** [BEMADEV/Room-Management#37]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

With the internal testing version v2.5.5.14, resources and locations cannot be removed from a reservation. This looks related to the new triggers on Resources and Locations.

### Expected Behavior

It should be possible to delete resources and locations from a reservation.

### Actual Behavior

Removal does not work, and an exception is thrown:
![image](https://github.com/BEMADEV/Room-Management/assets/4174527/c6088c96-9b8c-40c0-aa95-8ff9a55792d7)

### Steps to Reproduce

1. Create a reservation, add resources or locations
2. Save the reservation
3. Edit the newly saved reservation
4. Attempt to delete a reservation or resource

### Rock Version

16.4

### Plugin Version

2.5.5.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Fixed issue
