### ISSUE TITLE
Exception on v16.6alpha

### ISSUE THREAD

**Issue by JimMichael** [BEMADEV/Room-Management#45]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

While testing Rock v1.16.6.1 (alpha1) we saw no obvious problems/exceptions with Room Management plugin v2.4.7.14 that happened to be installed on our test instance. After upgrading plugin to v2.5.9.14 we now see an exception on Rock startup.

### Expected Behavior

No room management plugin exception on v16.6

### Actual Behavior

We see this exception now:
![image](https://github.com/user-attachments/assets/9a328b5e-147f-405c-a1f8-a595ba12dce3)

### Steps to Reproduce

1. Install v16.6 alpha
2. Upgrade to Room Management v2.5.9.14
3. Observe exception in log

### Rock Version

1.16.6.1

### Plugin Version

2.5.9.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Hi Jim! For an emergency fix, you can replace that method with AddOrReplace. We'll roll out an updated version tomorrow

**Comment by JimMichael** [comment]
@tcavaletto Thanks! Just a heads up that Spark seems to be saying this is a problem on the Rock side. There's a discussion about it in the alpha-testers channel of Rocket.Chat if you have access to that.
